<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Redefinir senha</name>
   <tag></tag>
   <elementGuidId>3ff3c90f-bcfd-4db4-bd9b-fffe30798a5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/table/tbody/tr[2]/td/table[2]/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.x_es-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://172.16.1.21:6200/account/reset-password?email=mayara.moraes@dataplace.com.br&amp;token=CfDJ8C/oPlTY4OBIpEjvbeADczZLlLg5I/IZXeMWeD6eaqjiJ9h8NZjAtZjggy0nH8eK48bnUMg7YLU+yCi+MMzdT5HI4LAtQQVRrhsxKQQQZTp6BdMEh3dhf3zQSMBG9xb70Or2WYL5ky6+NBV3uC61KzpaMKqYvZNInSk870WIDNIcFQ6IgmWtVFfrw9Yxf3DPrcwPUesMfYE8ObD2J59f/Dte4dqKSObE3EMtRJmaRlnl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth</name>
      <type>Main</type>
      <value>NotApplicable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x_es-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-linkindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Redefinir senha</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;_2qM5JFJlSDFbw17aZw2PSp&quot;]/div[@class=&quot;LXc0AFtlSiX4R6aYow6BV&quot;]/div[@class=&quot;_2RHr4NuGmNruCPzxGzLjJU&quot;]/div[@class=&quot;_1smn6wvuqmljaEvi28SQVz _3K8D6IBdXNd-lVODEK5i_X customScrollBar&quot;]/div[1]/div[@class=&quot;_3BpnlUwgtfNUWLoQytJYRy&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;_3BL964mseejjC_nzEeda9o NN4ve7-zXI11J6Er51ULd&quot;]/div[@class=&quot;_2Qk4AbDuWwkuLB005ds2jm QMubUjbS-BOly_BTHEZj7 allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_1171&quot;]/div[1]/div[@class=&quot;x_es-wrapper-color&quot;]/div[@class=&quot;ugHd8hEKTmP3zNa_t33nm&quot;]/table[@class=&quot;x_es-wrapper&quot;]/tbody[1]/tr[2]/td[1]/table[@class=&quot;x_es-content&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;x_es-content-body&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/span[@class=&quot;x_es-button-border&quot;]/a[@class=&quot;x_es-button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/table/tbody/tr[2]/td/table[2]/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/span/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Redefinir senha')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Para:'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responder'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reencaminhar'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Redefinir senha']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://172.16.1.21:6200/account/reset-password?email=mayara.moraes@dataplace.com.br&amp;token=CfDJ8C/oPlTY4OBIpEjvbeADczZLlLg5I/IZXeMWeD6eaqjiJ9h8NZjAtZjggy0nH8eK48bnUMg7YLU+yCi+MMzdT5HI4LAtQQVRrhsxKQQQZTp6BdMEh3dhf3zQSMBG9xb70Or2WYL5ky6+NBV3uC61KzpaMKqYvZNInSk870WIDNIcFQ6IgmWtVFfrw9Yxf3DPrcwPUesMfYE8ObD2J59f/Dte4dqKSObE3EMtRJmaRlnl']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
   </webElementXpaths>
</WebElementEntity>
