<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-account-root_LoginNome de usurio ou end_c25f7d</name>
   <tag></tag>
   <elementGuidId>ebfd773c-3d14-4268-a72e-922326d0cb58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-account-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-account-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-account-root</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LoginNome de usuário ou endereço de emailSenha Login Esqueci minha senha</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-account-root[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-account-root</value>
   </webElementXpaths>
</WebElementEntity>
